version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.10
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '20.9'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App
          command: |
            cd bankchurn-api 
            railway link bb3cf290-0663-44ac-8ce6-be7bb9d6344d 7b97f439-549b-4b99-b0c5-44d4870b3399
            railway up --detach


tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 1
  deploy_pipeline:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only:
                - main
